// Bildebeskrivelser for generering av rettbilder (Qwen-Image, Apache 2.0).
// Nøkkel = oppskrifts-id. STYLE legges til hver beskrivelse.
export const STYLE = 'Realistic food photography, served on a plate or in a bowl on a light wooden kitchen table in a Norwegian home, natural window light, soft shadows, shallow depth of field, appetizing, no text, no logos, no people, no hands.';

export const PROMPTS = {
  'kylling-karri': 'Thai red curry with chicken pieces and red bell pepper in creamy orange coconut sauce, bowl of white jasmine rice, fresh coriander on top.',
  'tikka-masala': 'Chicken tikka masala in rich orange tomato cream sauce in a bowl, white basmati rice on the side, dollop of yoghurt and coriander.',
  'kylling-wok': 'Chicken stir fry with egg noodles, broccoli, carrot strips and sugar snap peas glazed in soy sauce, served in a wok pan.',
  'kylling-fajitas': 'Sizzling chicken fajitas with strips of red and yellow bell pepper and red onion in a cast iron pan, warm tortillas, sour cream, guacamole and grated cheese in small bowls.',
  'ovnskylling-lar': 'Roasted golden crispy chicken thighs on a baking tray with roasted potatoes, carrots and red onion wedges, sprinkled with paprika and herbs.',
  'kylling-lar-ris': 'Pan fried crispy glazed chicken thigh fillets sliced on a plate with white rice and bright green steamed broccoli.',
  'helstekt-kylling': 'Whole roast chicken with golden crispy skin on a serving platter, roasted potatoes, lemon halves and garlic, green salad with cherry tomatoes beside.',
  'kylling-pasta-pesto': 'Penne pasta with green basil pesto, pan fried chicken pieces and halved cherry tomatoes, grated parmesan on top.',
  'kyllingburger': 'Chicken burger with a juicy patty, tomato slices and creamy coleslaw in a toasted brioche bun, extra coleslaw on the side.',
  'pulled-chicken-taco': 'Soft flour tortilla tacos filled with pulled chicken, sweet corn, shredded lettuce, sour cream and grated cheese.',
  'kyllingsuppe': 'Clear chicken soup with chunks of chicken, carrot slices, leek and potato cubes in a white bowl.',
  'taco': 'Norwegian Friday taco night: soft tortillas, seasoned ground beef in a cast iron pan, bowls of shredded lettuce, diced tomatoes, cucumber, sweet corn, grated cheese, sour cream and sliced avocado.',
  'spaghetti-bolognese': 'Spaghetti bolognese with rich minced beef tomato sauce on top, grated parmesan and a basil leaf.',
  'lasagne': 'Slice of homemade beef lasagne showing layers of pasta, meat sauce and bechamel with golden melted cheese crust, baking dish behind.',
  'hamburger': 'Homemade beef cheeseburger with melted cheese, lettuce, tomato and red onion in a sesame bun, rustic potato wedges on the side.',
  'kjottboller-tomatsaus': 'Beef meatballs in tomato sauce over spaghetti, grated parmesan and fresh basil.',
  'kjottboller-brun': 'Swedish style meatballs in brown gravy with creamy mashed potatoes and green peas.',
  'kjottkaker': 'Norwegian kjøttkaker: flat beef patties in brown gravy with boiled potatoes and creamed cabbage (kålstuing).',
  'karbonader': 'Pan fried beef patties topped with soft caramelized fried onions, boiled potatoes and carrots.',
  'karbonadedeig-wok': 'Stir fried ground beef with colourful wok vegetables in sweet and sour glaze, bowl of white rice.',
  'karbonade-burger': 'Lean beef burger with fried onions, lettuce, tomato and mustard in a soft bun.',
  'chili-con-carne': 'Chili con carne with ground beef, kidney beans and tomatoes in a bowl, white rice on the side, sliced red chili.',
  'biffwok': 'Beef strips stir fried with egg noodles, broccoli and red bell pepper in soy ginger sauce in a wok.',
  'storfegryte': 'Hearty autumn beef stew with chunks of beef, carrots, swede and celeriac in rich brown sauce in a cast iron pot, boiled potatoes.',
  'koteletter': 'Pan fried pork chops with roasted potatoes, carrots and red onion wedges.',
  'svinefilet': 'Sliced pork tenderloin with creamy mushroom sauce, boiled potatoes and steamed broccoli.',
  'svin-sweet-sour': 'Sweet and sour pork with pieces of bell pepper and onion in glossy red sauce, bowl of white rice.',
  'pulled-pork-burger': 'Pulled pork burger with barbecue glazed shredded pork and creamy coleslaw in a brioche bun.',
  'polse-potetstappe': 'Norwegian sausages (wiener pølser) with creamy mashed potatoes, green peas and a little mustard.',
  'polsegryte': 'Sausage stew with sliced sausages, tomato sauce, bell pepper and beans in a pot, white rice.',
  'carbonara': 'Spaghetti carbonara with crispy bacon pieces, creamy egg and parmesan sauce and cracked black pepper.',
  'spareribs': 'Glazed oven baked pork spareribs on a board with crispy potato wedges and coleslaw.',
  'baconpasta': 'Creamy pasta with crispy bacon and broccoli florets, grated parmesan.',
  'farikal': 'Norwegian fårikål: lamb pieces on the bone stewed with large cabbage wedges and whole black peppercorns in a pot, boiled potatoes on the side.',
  'lammeskiver': 'Pan fried slices of leg of lamb with root vegetable mash (rotmos) and melted butter.',
  'lammegryte': 'Lamb stew with tomato, white beans and carrots in a cast iron pot, bowl of couscous.',
  'lammewok': 'Stir fried lamb strips with red bell pepper and red onion, white rice.',
  'ovnslaks': 'Oven baked salmon fillet with lemon wedges, boiled new potatoes and steamed broccoli.',
  'laks-teriyaki': 'Glazed soy and sesame salmon fillet with white rice, broccoli and carrot sticks, sesame seeds.',
  'laks-pasta': 'Creamy pasta with salmon chunks and baby spinach, lemon zest.',
  'orret': 'Pan fried trout fillet with crispy skin, boiled potatoes, Norwegian cucumber salad and sour cream.',
  'torsk': 'Pan fried cod fillet with crispy bacon bits, mashed carrot (gulrotstuing) and boiled potatoes.',
  'sei': 'Breaded pan fried pollock fillets with remoulade, boiled potatoes and carrots.',
  'fiskesuppe': 'Creamy Bergen fish soup with chunks of white fish and salmon, carrots and leek in a bowl, sour cream on top.',
  'fiskekaker': 'Norwegian fish cakes (fiskekaker) with boiled potatoes, carrots, broccoli and melted butter.',
  'fiskepudding': 'Slices of Norwegian fish pudding (fiskepudding) with white sauce, boiled potatoes and carrots.',
  'reketaco': 'Shrimp tacos with garlic scampi, shredded cabbage, avocado, sour cream, chili and coriander in soft tortillas.',
  'reker-brod': 'Norwegian shrimp feast: big bowl of whole pink shrimps, white bread slices, mayonnaise, lemon wedges and lettuce.',
  'tunfiskpasta': 'Pasta with tuna and tomato sauce, fresh parsley.',
  'falafel': 'Falafel in pita bread with lettuce, tomato, cucumber, red onion and tzatziki.',
  'omelett': 'Oven baked vegetable omelette with bell pepper, mushrooms, tomato and melted cheese in a baking dish, green salad.',
  'pizza': 'Homemade vegetarian pizza with tomato sauce, mozzarella, bell pepper, mushrooms and red onion on a wooden board.',
  'pizza-pepperoni': 'Homemade pepperoni pizza with melted cheese on a wooden board.',
  'pasta-pesto-veg': 'Pasta with basil pesto, cherry tomatoes, mozzarella pieces and baby spinach.',
  'linsesuppe': 'Red lentil soup with tomato and coconut in a bowl, swirl of coconut milk.',
  'kikertgryte': 'Chickpea curry with spinach in coconut sauce, white rice.',
  'vegetar-taco': 'Vegetarian tacos with roasted sweet potato cubes, black beans, corn, avocado, sour cream and cheese in soft tortillas.',
  'blomkalsuppe': 'Creamy white cauliflower soup in a bowl with a slice of bread.',
  'grateng': 'Broccoli and cauliflower gratin with golden cheese crust in a baking dish.',
  'shakshuka': 'Shakshuka with eggs poached in spicy tomato and bell pepper sauce in a cast iron pan, crusty bread.',
  'sotpotet-feta': 'Roasted sweet potato cubes with crispy chickpeas, crumbled feta, red onion and baby spinach on a tray.',
  'gronnsakswok': 'Vegetable stir fry with egg noodles, scrambled egg and colourful wok vegetables in soy sauce.',
  'tomatsuppe': 'Norwegian tomato soup with macaroni and halved boiled eggs in a bowl.',
  'vegetar-chili': 'Vegetarian chili with beans, sweet corn and bell pepper in tomato sauce, white rice.',
  'soppasta': 'Creamy mushroom pasta with sliced mushrooms and grated parmesan.',
};
