// Søkeord for bilder av rettene. pexels = engelsk søk på pexels.com,
// commons = søk på Wikimedia Commons (brukes for norske klassikere).
export const QUERIES = {
  'kylling-karri': { pexels: 'thai red curry chicken rice' },
  'kylling-wok': { pexels: 'chicken noodle stir fry' },
  'kylling-fajitas': { pexels: 'chicken fajitas' },
  'ovnskylling-lar': { pexels: 'roasted chicken thighs vegetables' },
  'kylling-lar-ris': { pexels: 'glazed chicken rice broccoli' },
  'helstekt-kylling': { pexels: 'whole roast chicken potatoes' },
  'kylling-pasta-pesto': { pexels: 'chicken pesto pasta' },
  'kyllingburger': { pexels: 'chicken burger coleslaw' },
  'pulled-chicken-taco': { pexels: 'chicken soft tacos' },
  'kyllingsuppe': { pexels: 'chicken vegetable soup' },
  'taco': { pexels: 'taco night ground beef tortillas' },
  'spaghetti-bolognese': { pexels: 'spaghetti bolognese' },
  'lasagne': { pexels: 'lasagna' },
  'hamburger': { pexels: 'homemade cheeseburger' },
  'kjottboller-tomatsaus': { pexels: 'meatballs tomato sauce spaghetti' },
  'kjottboller-brun': { pexels: 'swedish meatballs mashed potatoes', commons: 'kjøttboller' },
  'kjottkaker': { pexels: 'meat patties gravy potatoes', commons: 'kjøttkaker' },
  'karbonader': { pexels: 'beef patty fried onions', commons: 'karbonader' },
  'karbonadedeig-wok': { pexels: 'ground beef stir fry rice' },
  'karbonade-burger': { pexels: 'beef burger onions' },
  'chili-con-carne': { pexels: 'chili con carne' },
  'biffwok': { pexels: 'beef noodle stir fry' },
  'storfegryte': { pexels: 'beef stew pot' },
  'koteletter': { pexels: 'pork chops roasted vegetables' },
  'svinefilet': { pexels: 'pork tenderloin mushroom sauce' },
  'svin-sweet-sour': { pexels: 'sweet and sour pork' },
  'pulled-pork-burger': { pexels: 'pulled pork burger' },
  'polse-potetstappe': { pexels: 'sausages mashed potatoes peas', commons: 'pølser potetmos' },
  'polsegryte': { pexels: 'sausage stew tomato' },
  'carbonara': { pexels: 'spaghetti carbonara' },
  'spareribs': { pexels: 'pork ribs' },
  'baconpasta': { pexels: 'creamy pasta bacon broccoli' },
  'farikal': { commons: 'fårikål' },
  'lammeskiver': { pexels: 'lamb steak mash' },
  'lammegryte': { pexels: 'lamb stew beans' },
  'lammewok': { pexels: 'lamb stir fry peppers' },
  'ovnslaks': { pexels: 'baked salmon potatoes broccoli' },
  'laks-teriyaki': { pexels: 'teriyaki salmon rice' },
  'laks-pasta': { pexels: 'salmon pasta spinach' },
  'orret': { pexels: 'pan fried trout fillet' },
  'torsk': { pexels: 'cod fillet bacon', commons: 'torsk middag' },
  'sei': { pexels: 'breaded fish fillet potatoes' },
  'fiskesuppe': { pexels: 'creamy fish soup', commons: 'fiskesuppe' },
  'fiskekaker': { pexels: 'fish cakes potatoes', commons: 'fiskekaker' },
  'fiskepudding': { commons: 'fiskepudding' },
  'reketaco': { pexels: 'shrimp tacos' },
  'reker-brod': { pexels: 'shrimp bread mayonnaise lemon', commons: 'reker loff' },
  'tunfiskpasta': { pexels: 'tuna pasta tomato' },
  'falafel': { pexels: 'falafel pita' },
  'omelett': { pexels: 'vegetable frittata' },
  'pizza': { pexels: 'vegetable pizza' },
  'pizza-pepperoni': { pexels: 'pepperoni pizza' },
  'pasta-pesto-veg': { pexels: 'pesto pasta tomato mozzarella' },
  'linsesuppe': { pexels: 'red lentil soup' },
  'kikertgryte': { pexels: 'chickpea curry spinach' },
  'vegetar-taco': { pexels: 'sweet potato black bean tacos' },
  'blomkalsuppe': { pexels: 'cauliflower soup' },
  'grateng': { pexels: 'cauliflower broccoli gratin' },
  'shakshuka': { pexels: 'shakshuka' },
  'sotpotet-feta': { pexels: 'roasted sweet potato chickpeas feta' },
  'gronnsakswok': { pexels: 'vegetable noodle stir fry egg' },
  'tomatsuppe': { pexels: 'tomato soup egg', commons: 'tomatsuppe' },
  'vegetar-chili': { pexels: 'vegetarian chili beans' },
  'soppasta': { pexels: 'creamy mushroom pasta' },
};
